version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - microservice-network
  rabbitmq:
    image: rabbitmq:3.11.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microservice-network
  client:
    build: .
    command:
      - python
      - client.py
    image: client
    networks:
      - microservice-network
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=5000
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_PORT=5672
  server:
    build: .
    command:
      - python
      - server.py
    image: server
    volumes:
      - .:/app
    ports:
      - 8080:8080
    networks:
      - microservice-network
    environment:
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_PORT=5672
  parser:
    build: .
    command:
      - python
      - parser.py
    image: parser
    networks:
      - microservice-network
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_PORT=5672
  api:
    build: .
    command:
      - python
      - elasticsearch_api.py
    image: api
    networks:
      - microservice-network
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    expose:
      - 5000
    volumes:
      - ./api:/app

  nginx:
    image: nginx
    networks:
      - microservice-network
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  elasticsearch-data:

networks:
  microservice-network:
